name: Duplicate Auth-Feature PR to Staging

on:
  push:
    branches:
      - develop

jobs:
  duplicate-auth-feature:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Fetch all branches and tags
        run: git fetch --all

      - name: Get PR commits from develop with auth-feature scope
        id: auth_commits
        run: |
          # Fetch the list of commit hashes that match the scope
          COMMITS=$(git log --pretty=format:"%H" --grep="^feat(auth-feature):" origin/develop)
          echo "$COMMITS" > auth_commits.txt
          echo "::set-output name=commits::$COMMITS"

      - name: Checkout staging branch
        run: git checkout staging

      - name: Cherry-pick auth-feature commits into staging
        run: |
          while read -r COMMIT; do
            git cherry-pick "$COMMIT" || exit 1
          done < auth_commits.txt

      - name: Push changes to staging
        run: |
          git push origin staging

      - name: Create PR from staging to develop
        uses: peter-evans/create-pull-request@v5
        with:
          title: "AUTH Feature point to staging branch"
          head: staging
          base: develop
          body: "This PR includes commits related to the AUTH feature from the `develop` branch."
          labels: "automated"
